# Generated by Django 4.2.23 on 2025-07-17 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('dni', 'DNI'), ('passport', 'Pasaporte'), ('license', 'Licencia de Conducir'), ('other', 'Otro')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('document_front_image', models.ImageField(upload_to='id_verifications/fronts/')),
                ('document_back_image', models.ImageField(blank=True, null=True, upload_to='id_verifications/backs/')),
                ('selfie_image', models.ImageField(blank=True, null=True, upload_to='id_verifications/selfies/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document_type', 'document_number')},
            },
        ),
    ]
