# Generated by Django 4.2.23 on 2025-07-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdentityVerification',
        ),
    ]
