# Generated by Django 4.2.23 on 2025-07-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branch_city_alter_branch_region'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='branches.branch'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
