# Generated by Django 4.2.21 on 2025-06-23 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido. Ejemplo: +56912345678 o 912345678.', regex='^(\\+56)?\\s?9\\d{8}$')], verbose_name='Phone'),
        ),
    ]
