# Generated by Django 4.2.21 on 2025-06-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_is_active_branch_latitude_branch_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
